package net.japanesehunter.worldcreate.input

/**
 * Represents a user input event from keyboard or mouse devices.
 *
 * Subtypes capture the specific kind of input along with relevant payload data.
 * Implementations are immutable value types suitable for use in event streams.
 */
sealed interface InputEvent

/**
 * Represents a key press event.
 *
 * @param code the physical key code following the KeyboardEvent.code convention.
 * @param repeat true if this event was generated by key auto-repeat.
 */
data class KeyDown(
  val code: String,
  val repeat: Boolean,
) : InputEvent

/**
 * Represents a key release event.
 *
 * @param code the physical key code following the KeyboardEvent.code convention.
 */
data class KeyUp(val code: String) : InputEvent

/**
 * Represents mouse pointer movement.
 *
 * @param deltaX the horizontal movement in device pixels since the last event.
 * @param deltaY the vertical movement in device pixels since the last event.
 */
data class MouseMove(
  val deltaX: Double,
  val deltaY: Double,
) : InputEvent

/**
 * Represents a mouse button press event.
 *
 * @param button the button index where 0 is the primary button.
 */
data class MouseDown(val button: Int) : InputEvent

/**
 * Represents a mouse button release event.
 *
 * @param button the button index where 0 is the primary button.
 */
data class MouseUp(val button: Int) : InputEvent

/**
 * Represents a mouse wheel scroll event.
 *
 * @param deltaX the horizontal scroll amount in pixels.
 * @param deltaY the vertical scroll amount in pixels.
 */
data class Wheel(
  val deltaX: Double,
  val deltaY: Double,
) : InputEvent
